version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=nanoandrew4
      - MYSQL_PASSWORD=securepassword
      - MYSQL_DATABASE=sampledatabase
  web:
    image: restfulcatalog
    restart: on-failure
    network_mode: "host"
    ports:
      - "80:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=nanoandrew4
      - DATABASE_PASSWORD=securepassword
      - DATABASE_NAME=sampledatabase
      - DATABASE_PORT=3306